"""Create roadmaps table

Revision ID: 2119f02ddc17
Revises: 267bf83a8c79
Create Date: 2026-07-14 11:15:12.435543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2119f02ddc17'
down_revision = '267bf83a8c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('career_goal', sa.String(length=100), nullable=False),
    sa.Column('estimated_timeline', sa.String(length=50), nullable=False),
    sa.Column('weekly_plan', sa.JSON(), nullable=False),
    sa.Column('recommended_courses', sa.JSON(), nullable=False),
    sa.Column('suggested_projects', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmaps_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmaps_user_id'))

    op.drop_table('roadmaps')
    # ### end Alembic commands ###
