"""Create resume_analyses table

Revision ID: 267bf83a8c79
Revises: 99d95c86e747
Create Date: 2026-07-13 16:56:56.635653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267bf83a8c79'
down_revision = '99d95c86e747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('keyword_suggestions', sa.JSON(), nullable=False),
    sa.Column('improved_bullets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_analyses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_analyses_user_id'))

    op.drop_table('resume_analyses')
    # ### end Alembic commands ###
