"""Create project_recommendations table

Revision ID: d9c0fb00093d
Revises: 53c9fde4e9c5
Create Date: 2026-07-14 11:36:37.165564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c0fb00093d'
down_revision = '53c9fde4e9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interests', sa.String(length=255), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_recommendations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_recommendations_user_id'))

    op.drop_table('project_recommendations')
    # ### end Alembic commands ###
